== ble.startAdvert() ==


=== Description ===

Starts advertising over BLE. This optionally takes a parameter of type
link:../ble_advert_settings/[BLE_Advert_Settings]. These
settings do not actually determine what is sent over the air, so this
function is independent of
link:../ble_setadvertname/[`ble.setAdvertName()`]
and
link:../ble_setadvertdata/[`ble.setAdvertData()`]
(for advanced BLE users).

=== Syntax ===

ble.startAdvert();

ble.startAdvert(&advertSettings);

=== Parameters ===

**&advertSettings**: Pointer to an instance of
link:../ble_advert_settings/[BLE_Advert_Settings].
If not provided, indefinite connectable advertising with a 100ms
interval that stops during connection and restarts afterwards will be
used.

=== Returns ===

link:../ble_error/[Status code]

=== Example === (default settings)

Indefinite connectable advertising every 100ms that restarts on
connection termination.
[source,arduino]
----
    #include <BLE.h>

    void setup() {
      ble.begin();
      ble.startAdvert();
    }

    void loop() {
      ble.handleEvents();
    }
----
=== Example === (custom settings)

Indefinite nonconnectable (e.g. for a simple beacon) advertisement every
900ms. Note that the last member, the connected behavior, of
advertSettings has no effect because this is nonconnectable advertising.
[source,arduino]
----
    #include <BLE.h>

    BLE_Advert_Settings advertSettings =
    {
      BLE_ADV_MODE_NONCONN,
      0,
      1440, // 1440*0.625ms = 900ms
      BLE_ADV_RESTART_ON_CONN_EST
    }

    void setup() {
      ble.begin();
      ble.startAdvert(&advertSettings);
    }

    void loop() {
      ble.handleEvents();
    }
----