== ble.setLogLevel() ==


=== Description ===

Sets what type of information should be logged to the Energia serial
monitor.

=== Syntax ===

ble.setLogLevel(newLogLevel);

=== Parameters ===

**newLogLevel**: A link:/reference/en/language/structure/bitwise-operators/bitwiseand[bitwise OR]
of the different types of desired logging information.

-   BLE_LOG_NONE: Log nothing. This is the default level when this
    function is not called.
-   BLE_LOG_ERRORS: Log whenever an internal function call or message
    from the NP returns an error code.
-   BLE_LOG_RPCS: Log remote procedure calls (RPC's), which are
    essentially commands or requests sent from the AP to the NP.
-   BLE_LOG_REC_MSGS: Log messages received by the AP from the NP.
    These are mostly confirmations that a requested action occurred, or
    notifications of some event happening.
-   BLE_LOG_MSGS: Log both BLE_LOG_RPCS and BLE_LOG_MSGS.
-   BLE_LOG_CHARACTERISTICS: Log reads and writes of BLE
    characteristics by both the AP and the wirelessly connected client.
-   BLE_LOG_ALL: Logs all above information.

 

=== Returns ===

Nothing

=== Example ===
[source,arduino]
----
    #include "BLE.h"

    void setup() {
      ble.setLogLevel(BLE_LOG_ALL);
      ble.begin();
    }
----