== ble.setAdvertName() ==


=== Description ===

Sets the advertised name of the device. This is what is displayed when
scanning for Bluetooth devices on a laptop or cell phone.

=== Syntax ===

ble.setAdvertName(advertName); // link:/reference/en/language/variables/data-types/string/[char array] or string literal

ble.setAdvertName(&advertName); // link:/reference/en/language/variables/data-types/stringobject/[String object]

=== Parameters ===

**advertName**: Either a link:/reference/en/language/variables/data-types/string/char array] or a pointer to a link:/reference/en/language/variables/data-types/stringobject/[String object].

=== Returns ===

link:../ble_error/[Status code]

=== Example === (string literal)
[source,arduino]
----
    #include <BLE.h>

    void setup() {
      ble.begin();
      ble.setAdvertName("Energia BLE");
      ble.startAdvert();
    }
----
=== Example === (link:/reference/en/language/variables/data-types/string/[char array])
[source,arduino]
----
    #include <BLE.h>
    char advertName[] = "Energia BLE";
    void setup() {
      ble.begin();
      ble.setAdvertName(advertName);
      ble.startAdvert();
    }
----
=== Example === (link:/reference/en/language/variables/data-types/stringobject/[String object])
[source,arduino]
----
    #include <BLE.h>
    String advertName = String("Energia BLE");
    void setup() {
      ble.begin();
      ble.setAdvertName(advertName);
      ble.startAdvert();
    }
----