*EthernetUDP*.read()
--------------------

#### Description

Reads UDP data from the specified buffer. If no arguments are given, it
will return the next character in the buffer. This function can only be
successfully called after
[UDP.parsePacket()](http://energia.nu/reference/ethernet/ethernet_udpparsepacket/ "Ethernet_UDPParsePacket"){.wikilink}.

#### Syntax

UDP.read(); UDP.read(packetBuffer, <span
class="wikiword">MaxSize</span>);

#### Parameters

**packetBuffer**: buffer to hold incoming packets (char) **<span
class="wikiword">MaxSize</span>**: maximum size of the buffer (int)

#### Returns

char : returns the characters in the buffer

#### Example

    #include <SPI.h>        
    #include <Ethernet.h>
    #include <EthernetUdp.h>

    // Enter a MAC address and IP address for your controller below.
    // The IP address will be dependent on your local network:
    byte mac[] = { 0xDE, 0xAD, 0xBE, 0xEF, 0xFE, 0xED };
    IPAddress ip(192, 168, 1, 177);

    unsigned int localPort = 8888;      // local port to listen on

    // An EthernetUDP instance to let us send and receive packets over UDP
    EthernetUDP Udp;

    char packetBuffer[UDP_TX_PACKET_MAX_SIZE]; //buffer to hold incoming packet,

    void setup() {
      // start the Ethernet and UDP:
      Ethernet.begin(mac,ip);
      Udp.begin(localPort);

    }

    void loop() {

      int packetSize = Udp.parsePacket();
      if(packetSize)
      {
        Serial.print("Received packet of size ");
        Serial.println(packetSize);
        Serial.print("From ");
        IPAddress remote = Udp.remoteIP();
        for (int i =0; i < 4; i++)
        {
          Serial.print(remote[i], DEC);
          if (i < 3)
          {
            Serial.print(".");
          }
        }
        Serial.print(", port ");
        Serial.println(Udp.remotePort());

        // read the packet into packetBufffer
        Udp.read(packetBuffer,UDP_TX_PACKET_MAX_SIZE);
        Serial.println("Contents:");
        Serial.println(packetBuffer);
    }
    }

[Reference Home](http://energia.nu/reference/ "Reference"){.wikilink} ||
[Ethernet Library](http://energia.nu/reference/ethernet/ "Ethernet")
