== Example: Shift Register 4 (IC) ==

In this example we will be using a different type of shift register, called a Shift In register, or Parallel In Serial Out register. This device will help us increase the number of inputs we can handle with the microcontroller, the opposite of how our shift register that we worked with previously functions.

Based off of example here: http://playground.arduino.cc/Code/ShiftRegSN74HC165N

=== Hardware Required ===

* TI LaunchPad
* Breadboard
* 1x Shift in Register (SN74HC165N)
* 5x Push Buttons
* 18x Jumper Wires
* 16x 330 ohm resistor (optional)

 
=== Relevant Groundwork ===

The SN74HC165N is an 8-bit parallel-load or serial-in shift registers with complementary serial outputs available from the last stage. When the parallel load (PL) input is LOW, parallel data from the D0 to D7 inputs are loaded into the register asynchronously. When PL is HIGH, data enters the register serially at the Ds input and shifts one place to the right (Q0 → Q1 → Q2, etc.) with each positive-going clock transition. This feature allows parallel-to-serial converter expansion by tying the Q7 output to the DS input of the succeeding stage.

Note that any unused input pins should be grounded.

==== Code ====

[source,arduino]
----
include::content/guide/tutorials/other/sidekick/code/sidekick_shiftregister4.ino[]
----

=== Programming Challenge === 

Can you make different LED modes and display the mode on the segment display?

=== Troubleshooting ===

Code not uploading?

* Check for errors in Energia debug window. The compiler will tell you what is happening. Errors are in red text.
* Sometimes your LaunchPad gets stuck or hung up on the previous code. Unplug your LaunchPad and plug it back in to perform a full reset.  This is called a power on reset. Sometimes using the RESET button can work but taking away the power and letting the microcontroller fully reset is often best.
* If you have a failure to upload it could be your drivers are not properly installed. Energia will sometimes give the error “No unused FET Found” which means it can’t find a LaunchPad connected to your computer. Make sure you download the drivers for your operating system found on the Getting Started Guide.
* If you had no problem with the previous Blink example, your Energia should be correctly set up. Restart your LaunchPad and restart Energia IDE if you encounter any problems. Make sure to select the right serial port and board type under the Tools menu.

Buttons not responding?

* Make sure you properly uploaded the code and that you properly named your variables for the pins.

For additional support, try searching the Energia forums on 43oh.com. We believe in you to figure out any problems, now believe in yourself and find the solution!
