== Example: DAC (Digital to Analog IC) ==

Learn how to use a H-bridge motor driver to help us spin a small DC motor.

=== Hardware Required ===

* TI LaunchPad
* Breadboard
* TLC5615CP

=== Relevant Groundwork === 

In this example we will use a Digital to Analog converter.

==== Code ====

[source,arduino]
----
include::content/guide/tutorials/other/sidekick/code/sidekick_dac.ino[]
----

=== Troubleshooting ===

Code not uploading?

* Check for errors in Energia debug window. The compiler will tell you what is happening. Errors are in red text.
* Sometimes your LaunchPad gets stuck or hung up on the previous code. Unplug your LaunchPad and plug it back in to perform a full reset.  This is called a power on reset. Sometimes using the RESET button can work but taking away the power and letting the microcontroller fully reset is often best.
* If you have a failure to upload it could be your drivers are not properly installed. Energia will sometimes give the error “No unused FET Found” which means it can’t find a LaunchPad connected to your computer. Make sure you download the drivers for your operating system found on the Getting Started Guide.
* If you had no problem with the previous Blink example, your Energia should be correctly set up. Restart your LaunchPad and restart Energia IDE if you encounter any problems. Make sure to select the right serial port and board type under the Tools menu.

No Values?
* Make sure you properly connected the pins for clock, data, and chip select.

For additional support, try searching the Energia forums on 43oh.com. We believe in you to figure out any problems, now believe in yourself and find the solution!