== Pitch follower using the tone() function ==

This example shows how to use the `tone()` command to generate a pitch that follows the values of an analog input.

=== Hardware Required ===

* 8-ohm speaker
* 1 photocell
* 4.7K ohm resistor
* 100 ohm resistor
* Breadboard
* Hook up wire

=== Circuit ===

Image developed using http://fritzing.org/home/[Fritzing]. For more circuit examples, see the http://fritzing.org/projects/[Fritzing project page].

Connect one terminal of your speaker to digital pin 9 through a 100 ohm resistor, and its other terminal to ground. Power your photoresistor with 5V, and connect it to analog 0 with the addition of a 4.7K resistor to ground.

=== Schematic ===

=== Code ===

The code for this example is very simple. Just take an analog input and map its values to a range of audible pitches. Humans can hear from 20-20,000Hz, but 120-1500 usually works pretty well for this sketch.

You'll need to get the actual range of your analog input for the mapping. In the circuit shown, the analog input value ranged from about 400 to about 1000. Change the values in the `map()` command to match the range for your sensor.

The sketch is as follows:

----
/*
 Pitch followerPlays a pitch that changes based on a changing analog inputcircuit:
 * 8-ohm speaker on digital pin 9
 * photoresistor on analog 0 to 5V
 * 4.7K resistor on analog 0 to groundcreated 21 Jan 2010
 modified 31 May 2012
 by Tom Igoe, with suggestion from Michael Flynn
 modified 7 Feb 2014  
 by Mark Easley 
 This example code is in the public domain. 
 */ 
void setup() { 
  // initialize serial communications (for debugging only): 
  Serial.begin(9600); 
} 
void loop() { 
  // read the sensor: 
  int sensorReading = analogRead(A0); 
  // print the sensor reading so you know its range 
  Serial.println(sensorReading); 
  // map the analog input range (in this case, 400 - 1000 from the photoresistor) 
  // to the output pitch range (120 - 1500Hz) 
  // change the minimum and maximum input numbers below 
  // depending on the range your sensor's giving: 
  int thisPitch = map(sensorReading, 400, 1000, 120, 1500); 
  // play the pitch: 
  tone(9, thisPitch, 10); 
  delay(1);        // delay in between reads for stability 
}
----

=== See Also ===

* link:/reference/en/language/variables/data-types/string/array/[Array()]
* link:/reference/en/language/structure/control-struture/for/[for()]
* link:/reference/en/language/functions/advanced-io/tone/[tone()]
* link:/reference/en/language/functions/math/map/[map()]
* link:/guide/tutorials/digital/tutorial_tone/[Tone]:play a melody with a piezo speaker.
* link:/guide/tutorials/digital/tutorial_tone3/[SimpleKeyboard]:a three-key musical keyboard using force sensors and a piezo speaker.
* link:/guide/tutorials/digital/tutorial_tone2/[Tone 4]:play tones on multiple speakers sequentially.