= Prototyping Software to Make Things Easy =

11/20/17 MSP-EXP430FR2433 support added through board manager

The new MSP-EXP430FR2433 is a “replacement” for the value line MSP-EXP430G2. Support for the MSP-EXP430FR2433 has been added to the MSP430 core and made available through the board manager in Energia.

The pinmap for the MSP-EXP430FR2433 is available here: http://energia.nu/launchpad-msp430fr2433-pins-map/[MSP-EXP430FR2433 pinmap]

---
== So, what is this all about then? ==
Energia is an https://github.com/energia/energia[open-source] electronics prototyping platform started by Robert Wessels in January of 2012 with the goal to bring the Wiring and Arduino framework to the Texas Instruments MSP430 based LaunchPad. The Energia IDE is cross platform and supported on Mac OS, Windows, and Linux. Energia uses the http://mspgcc.sourceforge.net/[mspgcc] compiler by http://sourceforge.net/users/pabigot[Peter Bigot] and is based on the http://wiring.org.co/[Wiring] and http://arduino.cc/[Arduino] framework. Energia includes an integrated development environment (IDE) that is based on http://www.processing.org/[Processing]. Energia is also a portable framework/abstraction layer that can be used in other popular IDEs. Utilize a web browser based environment with CCS Cloud at http://dev.ti.com/[dev.ti.com]. Community maintained Energia plug-ins and integrations are available for http://energia.nu/download/#communitycontributedalternatives[Xcode, Visual Studio, and Code Composer Studio].

The foundation of http://energia.nu/[Energia] and http://arduino.cc/[Arduino] is the http://wiring.org.co/[Wiring] framework that is developed by Hernando Barragan. The framework is thoughtfully created with designers and artists in mind to encourage a community where both beginners and experts from around the world share ideas, knowledge and their collective experience. The Energia team adopts the philosophy of learning by doing and strives to make it easy to work directly with the hardware. Professional engineers, entrepreneurs, makers, and students can all benefit from the ease of use Energia brings to the microcontroller.

Energia started out to bring the Wiring and Arduino framework to the Texas Instruments MSP430 LaunchPad. Texas Instruments offers a http://www.ti.com/ww/en/launchpad/msp430_head.html[MSP430], http://www.ti.com/ww/en/launchpad/msp430_head.html[MSP432], http://www.ti.com/ww/en/launchpad/launchpads-connected.html[TM4C], http://www.ti.com/ww/en/launchpad/c2000_head.html[C2000], and http://www.ti.com/ww/en/launchpad/launchpads-connected.html[CC3200] LaunchPad. The LaunchPad is a low-cost microcontroller board that is made by Texas Instruments. The http://energia.nu/download[latest] release of Energia supports the majority of the LaunchPad product offerings.

video::bH5kSSXFSac[youtube]

Together with Energia, LaunchPad can be used to develop interactive objects, taking inputs from a variety of switches or sensors, and controlling a variety of lights, motors, and other physical outputs. LaunchPad projects can be stand-alone (only run on the Target Board, i.e. your LaunchPad), or they can communicate with software running on your computer (Host PC). You can also add wireless modules to enable communication over various types of RF including Wi-Fi, NFC, Bluetooth, Zigbee, cellular, and more.

More information about LaunchPad can be found on the TI site: http://www.ti.com/launchpad[www.ti.com/launchpad]

== Getting Started ==
To get started with Energia for your operating system (Energia works on Mac OS X, Linux and Windows), follow the instructions in the http://energia.nu/guide/[getting started guide]. Start learning by doing using the handy tutorials and example code provided in the tutorial section of the getting started guide. You can find important board setup instructions and pin maps on the right hand navigation links of the website.

The Energia APIs are documented in the http://energia.nu/reference/[reference] section. Find out how the core functions and library functions operate to be a more effective programmer.
