++++
<style>
h1 {
  text-align: center;
}
/* Acordeon styles */
.tab {
  position: relative;
  margin-bottom: 1px;
  width: 100%;
  color: #fff;
  overflow: hidden;
}
input {
  position: absolute;
  opacity: 0;
  z-index: -1;
}
label {
  position: relative;
  display: block;
  padding: 0 0 0 1em;
  background: #aaa;
  font-weight: bold;
  line-height: 3;
  cursor: pointer;
}
.blue label {
  background: #2980b9;
}
.tab-content {
  max-height: 0;
  overflow: hidden;
  background: #fff;
  color: #000;
  -webkit-transition: max-height .35s;
  -o-transition: max-height .35s;
  transition: max-height .35s;
}
.blue .tab-content {
  background: #3498db;
}
.tab-content p {
  margin: 1em;
}
/* :checked */
input:checked ~ .tab-content {
  max-height: 30em;
}
/* Icon */
label::after {
  position: absolute;
  right: 0;
  top: 0;
  display: block;
  width: 3em;
  height: 3em;
  line-height: 3;
  text-align: center;
  -webkit-transition: all .35s;
  -o-transition: all .35s;
  transition: all .35s;
}
input[type=checkbox] + label::after {
  content: "+";
}
input[type=radio] + label::after {
  content: "\25BC";
}
input[type=checkbox]:checked + label::after {
  transform: rotate(315deg);
}
input[type=radio]:checked + label::after {
  transform: rotateX(180deg);
}
</style>
++++

== Installing the LaunchPad drivers
=== For all Boards
All Boards need a udev rule to be able to program as a regular user (not root). To install these udev rules, follow the steps below:

. Download the udev rules: https://s3.amazonaws.com/energiaUS/files/71-ti-permissions.rules[TI udev rules]
. Open a terminal and execute the following command: sudo mv /71-ti-permissions.rules /etc/udev/rules.d/
. If your Linux distribution supports the service command you can active the new rules with sudo service udev restart. If your Linux distribution does not support this command or if you are not able to upload to the LaunchPad with Energia, then restart your computer to activate the rules.
. If your board is pulled in, unplug it and plug it back in. Not needed if you rebooted your computer.

++++
<div class="tab">
  <input id="tab-one" type="radio" name="tabs">
  <label for="tab-one">MSP-EXP432P401R LaunchPad</label>
  <div class="tab-content">
++++
No drivers are needed for Linux. To be able to run Energia as a regular user and access the Serial port and programmer you will need the udev rules installed as explained above.
++++
  </div>
</div>
++++


++++
<div class="tab">
  <input id="tab-two" type="radio" name="tabs">
  <label for="tab-two">CC3200 LaunchPad</label>
  <div class="tab-content">
    <p>
++++

Follow the instructions on link:/guide/install/cc3200-guide/[this page] for important jumper settings and firmware upgrade instructions.

If you run a recent version of Linux then the FTDI kernel driver that is needed for the CC3200 LaunchPad is already installed. The only thing you need to do is to tell Linux to use that driver when you plug in your CC3200 LaunchPad using a udev rules as explained above.
++++
    </p>
  </div>
</div>
++++

++++
<div class="tab">
  <input id="tab-three" type="radio" name="tabs">
  <label for="tab-three">All MSP-EXP430XXX LaunchPads</label>
  <div class="tab-content">
    <p>
++++
No drivers are needed for Linux. To be able to run Energia as a regular user and access the Serial port and programmer you will need the udev rules installed as explained above.
++++
  </div>
</div>
++++

++++
<div class="tab">
  <input id="tab-five" type="radio" name="tabs">
  <label for="tab-five">EK-TM4C123GXL, EK-TM4C1294XL and EK-LM4F120XL LaunchPad</label>
  <div class="tab-content">
    <p>
++++
No drivers are needed for these LaunchPad. To be able to run Energia as a regular user and access the Serial port and programmer you will need the udev rules installed as explained above.
++++
  </div>
</div>
++++

include::content/guide/install/toblink.adoc[]
