*WiFiServer*.write()
--------------------

#### Description

Write data to all the clients connected to a server.

#### Syntax

*server*.write(data)

#### Parameters

**data**: the value to write (byte or char)

#### Returns

byte : the number of bytes written. It is not necessary to read this.

#### Example

    #include <SPI.h>
    #include <WiFi.h>

    char ssid[] = "yourNetwork";
    char pass[] = "yourPassword";
    int status = WL_IDLE_STATUS;

    WiFiServer server(80);

    void setup() {
      // initialize serial:
      Serial.begin(9600);
      Serial.println("Attempting to connect to WPA network...");
      Serial.print("SSID: ");
      Serial.println(ssid);

      status = WiFi.begin(ssid, pass);
      if ( status != WL_CONNECTED) { 
        Serial.println("Couldn't get a wifi connection");
        while(true);
      } 
      else {
        server.begin();
      }
    }

    void loop() {
      // listen for incoming clients
      WiFiClient client = server.available();
      if (client == true) {
           // read bytes from the incoming client and write them back
        // to any clients connected to the server:
        server.write(client.read());
      }
    }

[Reference Home](http://energia.nu/reference/ "Reference"){.wikilink} ||
[WiFi Library](http://energia.nu/reference/wifi/ "WiFi")
