<span class="wikiword">WiFi</span>.setDNS()
-------------------------------------------

#### Description

`WiFi.setDNS()` allows you to configure the DNS (Domain Name System)
server.

#### Syntax

<span class="wikiword">WiFi</span>.setDNS(dns\_server1) <span
class="wikiword">WiFi</span>.setDNS(dns\_server1, dns\_server2)

#### Parameters

**dns\_server1**: the IP address of the primary DNS server
**dns\_server2**: the IP address of the secondary DNS server

#### Returns

Nothing

#### Example

This example shows how to set the Google DNS (8.8.8.8). You can set it
as an object <span class="wikiword">IPAddress</span>.

    #include <SPI.h>
    #include <WiFi.h>

    // the IP address for the shield:
    IPAddress dns(8, 8, 8, 8);  //Google dns  

    char ssid[] = "yourNetwork";    // your network SSID (name) 
    char pass[] = "secretPassword"; // your network password (use for WPA, or use as key for WEP)

    int status = WL_IDLE_STATUS;

    void setup()
    {  
      // Initialize serial and wait for port to open:
      Serial.begin(9600); 
      while (!Serial) {
        ; // wait for serial port to connect. Needed for Leonardo only
      }

      // check for the presence of the shield:
      if (WiFi.status() == WL_NO_SHIELD) {
        Serial.println("WiFi shield not present"); 
        while(true);  // don't continue
      } 

      // attempt to connect to Wifi network:
      while ( status != WL_CONNECTED) { 
        Serial.print("Attempting to connect to SSID: ");
        Serial.println(ssid);
        // Connect to WPA/WPA2 network. Change this line if using open or WEP network:    
        status = WiFi.begin(ssid, pass);

        // wait 10 seconds for connection:
        delay(10000);
      }

      // print your WiFi shield's IP address:
      WiFi.setDNS(dns);
      Serial.print("Dns configured.");
    }

    void loop () {
    }

[Reference Home](http://energia.nu/reference/ "Reference") || [WiFi
Library](http://energia.nu/reference/wifi/ "WiFi")
