<span class="wikiword">WiFiServer</span>()
------------------------------------------

#### Description

Creates a server that listens for incoming connections on the specified
port.

#### Syntax

Server(port);

#### Parameters

**port**: the port to listen on (int)

#### Returns

None

#### Example

    #include <SPI.h>
    #include <WiFi.h>

    char ssid[] = "myNetwork";          //  your network SSID (name) 
    char pass[] = "myPassword";   // your network password
    int status = WL_IDLE_STATUS;

    WiFiServer server(80);

    void setup() {
      // initialize serial:
      Serial.begin(9600);
      Serial.println("Attempting to connect to WPA network...");
      Serial.print("SSID: ");
      Serial.println(ssid);

      status = WiFi.begin(ssid, pass);
      if ( status != WL_CONNECTED) { 
        Serial.println("Couldn't get a wifi connection");
        while(true);
      } 
      else {
        server.begin();
        Serial.print("Connected to wifi. My address:");
        IPAddress myAddress = WiFi.localIP();
        Serial.println(myAddress);

      }
    }


    void loop() {

    }

[Reference Home](http://energia.nu/reference/ "Reference"){.wikilink} ||
[WiFi Library](http://energia.nu/reference/wifi/ "WiFi")
